services:
  app.dev:
    container_name: ncms_web
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PORT=${PORT}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${PORT}:3000
    depends_on:
      db.dev:
        condition: service_healthy
        restart: true
    volumes:
      - ./app:/app/app
      - ./public:/app/public
    profiles:
      - dev
  db.dev:
    container_name: ncms_db
    image: postgres:15-alpine
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    profiles:
      - dev
  app.prod:
    container_name: ncms_web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${PORT}:3000
    depends_on:
      db.prod:
        condition: service_healthy
        restart: true
    profiles:
      - prod
  db.prod:
    container_name: ncms_db
    image: postgres:15-alpine
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    profiles:
      - prod
volumes:
  db_data_dev:
  db_data_prod:
